services:
  # FastAPI Backend Service
  - type: web
    name: youtube-analytics-backend
    env: python
    region: oregon
    plan: free
    repo: https://github.com/AI-Answer/youtube-analytics-dashboard.git
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///youtube_analytics.db
      - key: CORS_ORIGINS
        value: "*"
      - key: ENVIRONMENT
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: YOUTUBE_CHANNEL_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
    
  # Next.js Frontend Service
  - type: web
    name: youtube-analytics-frontend
    env: node
    region: oregon
    plan: free
    repo: https://github.com/AI-Answer/youtube-analytics-dashboard.git
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: youtube-analytics-backend
          property: host
      - key: NODE_ENV
        value: production

databases:
  # We'll use disk storage for SQLite instead of a separate database service
  # The SQLite file will be stored on the persistent disk attached to the backend
