[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python -c "print(\"Build phase complete\")"']

[start]
cmd = 'chmod +x railway-start.sh && ./railway-start.sh'
